/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        'secondary-fixed-dim': '#e0c29b',
        'on-tertiary': '#ffffff',
        'on-secondary-container': '#786140',
        'on-primary': '#ffffff',
        'on-primary-fixed': '#1c1b1b',
        'on-error-container': '#93000a',
        'primary-fixed': '#e5e2e1',
        'surface-container-high': '#e9e8e7',
        background: '#fbf9f9',
        'inverse-on-surface': '#f2f0f0',
        'on-primary-fixed-variant': '#474646',
        tertiary: '#000000',
        error: '#ba1a1a',
        'surface-container-low': '#f5f3f3',
        'surface-tint': '#5f5e5e',
        'on-tertiary-fixed': '#1b1c19',
        outline: '#747878',
        'on-primary-container': '#858383',
        'error-container': '#ffdad6',
        'on-surface': '#1b1c1c',
        secondary: '#715b3b',
        'tertiary-fixed': '#e4e2dd',
        'on-surface-variant': '#444748',
        'inverse-surface': '#303031',
        'on-secondary-fixed-variant': '#584325',
        'on-background': '#1b1c1c',
        'secondary-fixed': '#fddeb5',
        'on-tertiary-fixed-variant': '#474744',
        'on-secondary': '#ffffff',
        'surface-dim': '#dbdad9',
        surface: '#fbf9f9',
        'surface-bright': '#fbf9f9',
        'on-tertiary-container': '#848480',
        'on-secondary-fixed': '#281802',
        'tertiary-fixed-dim': '#c8c6c2',
        primary: '#000000',
        'surface-container': '#efeded',
        'primary-container': '#1c1b1b',
        'outline-variant': '#c4c7c7',
        'surface-container-lowest': '#ffffff',
        'tertiary-container': '#1b1c19',
        'on-error': '#ffffff',
        'primary-fixed-dim': '#c8c6c5',
        'surface-variant': '#e3e2e2',
        'secondary-container': '#fddeb5',
        'inverse-primary': '#c8c6c5',
        'surface-container-highest': '#e3e2e2',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        'stack-sm': '16px',
        'stack-lg': '64px',
        'container-max': '1280px',
        unit: '8px',
        'stack-md': '32px',
        'margin-edge': '40px',
        gutter: '24px',
      },
      fontFamily: {
        'body-md': ['Manrope', 'sans-serif'],
        'body-lg': ['Manrope', 'sans-serif'],
        'headline-md': ['Noto Serif', 'serif'],
        'headline-lg': ['Noto Serif', 'serif'],
        'headline-xl': ['Noto Serif', 'serif'],
        'label-caps': ['Manrope', 'sans-serif'],
      },
      fontSize: {
        'body-md': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        'headline-md': ['24px', { lineHeight: '1.4', fontWeight: '400' }],
        'headline-lg': [
          '32px',
          { lineHeight: '1.3', letterSpacing: '-0.01em', fontWeight: '400' },
        ],
        'headline-xl': [
          '48px',
          { lineHeight: '1.2', letterSpacing: '-0.02em', fontWeight: '400' },
        ],
        'label-caps': [
          '12px',
          { lineHeight: '1.0', letterSpacing: '0.1em', fontWeight: '600' },
        ],
      },
    },
  },
  plugins: [],
};
